CREATE TABLE EMPLOYEE (EMPID INT,EMPNAME VARCHAR(10),EMPSALARY MONEY)

DROP TABLE EMPLOYEE
/* ROW WISE RANKING */

INSERT INTO EMPLOYEE VALUES (1,'JOHN',1200)
INSERT INTO EMPLOYEE VALUES (2,'PETER',1500)
INSERT INTO EMPLOYEE VALUES (3,'MICHEAL',1800)
INSERT INTO EMPLOYEE VALUES (4,'BRAD',200)
INSERT INTO EMPLOYEE VALUES (5,'COAL',1500)
INSERT INTO EMPLOYEE VALUES (6,'KIRAN',850)
INSERT INTO EMPLOYEE VALUES (7,'KUMAR',670)
INSERT INTO EMPLOYEE VALUES (8,'GAUTHAM',990)
INSERT INTO EMPLOYEE VALUES (9,'STEVE',1800)
INSERT INTO EMPLOYEE VALUES (10,'SMITH',2200)

SELECT *FROM EMPLOYEE

SELECT EMPID,EMPNAME,EMPSALARY,ROW_NUMBER() OVER (ORDER BY EMPSALARY DESC) AS RANK FROM EMPLOYEE

SELECT EMPID,EMPNAME,EMPSALARY,RANK() OVER (ORDER BY EMPSALARY ASC) AS RANK FROM EMPLOYEE

SELECT EMPID,EMPNAME,EMPSALARY,DENSE_RANK() OVER (ORDER BY EMPSALARY ASC) AS RANK FROM EMPLOYEE

/* GROUP BY RANKING */
INSERT INTO EMPLOYEE VALUES (1,'JOHN',1200)
INSERT INTO EMPLOYEE VALUES (1,'JAMES',1400)
INSERT INTO EMPLOYEE VALUES (1,'JACKSON',1200)
INSERT INTO EMPLOYEE VALUES (1,'PRIYA',1300)
INSERT INTO EMPLOYEE VALUES (1,'KAVITHA',2000)

INSERT INTO EMPLOYEE VALUES (2,'MIKE',100)
INSERT INTO EMPLOYEE VALUES (2,'MICHEAL',200)
INSERT INTO EMPLOYEE VALUES (2,'KIRAN',400)
INSERT INTO EMPLOYEE VALUES (2,'KUMAR',200)
INSERT INTO EMPLOYEE VALUES (2,'KRISHNA',300)

INSERT INTO EMPLOYEE VALUES (3,'PRASANA',3200)
INSERT INTO EMPLOYEE VALUES (3,'PAVAN',4800)



SELECT EMPID,EMPNAME,EMPSALARY,ROW_NUMBER() OVER (PARTITION BY EMPID ORDER BY EMPSALARY ASC) AS RANK FROM EMPLOYEE

SELECT EMPID,EMPNAME,EMPSALARY,RANK() OVER (PARTITION BY EMPID ORDER BY EMPSALARY ASC) AS RANK FROM EMPLOYEE

SELECT EMPID,EMPNAME,EMPSALARY,DENSE_RANK() OVER (PARTITION BY EMPID ORDER BY EMPSALARY ASC) AS RANK FROM EMPLOYEE
