/* DDL OPERATIONS */
USE AMAZON

/* creating table in the database */
CREATE TABLE EMPLOYEES_DATA (EMPID INT,
                             EMPNAME CHAR(10),
							 EMPSAL MONEY,
							 EMPAGE TINYINT)

/* ALTER TECH 1: */
ALTER TABLE EMPLOYEES_DATA ALTER COLUMN EMPNAME VARCHAR(10)

/* ALTER TECH 2: */
ALTER TABLE EMPLOYEES_DATA ADD EMPLOC CHAR(10)

/* ALTER TECH 3: */
ALTER TABLE EMPLOYEES_DATA DROP COLUMN EMPLOC


/* CHANGING THE COLUMN NAME */
SP_RENAME 'EMPLOYEES_DATA.EMPSAL','SALARY'



/* OPEN THE TABLE */
/* *-> MEANS ALL COLUMNS */

SELECT *FROM EMPLOYEES_DATA

SELECT EMPID,EMPAGE FROM EMPLOYEES_DATA

/* DML OPERATIONS */

INSERT:

INSERT INTO EMPLOYEES_DATA VALUES (1,'JOHN',1200,27)

INSERT INTO EMPLOYEES_DATA VALUES (2.2,'PETER',1500,15)

INSERT INTO EMPLOYEES_DATA VALUES (5.87,'BRAD',1800,14)

INSERT INTO EMPLOYEES_DATA VALUES ('12','SMITH',1900,18)

INSERT INTO EMPLOYEES_DATA VALUES (3,'SRINU',2300,473289)

INSERT INTO EMPLOYEES_DATA VALUES (473289,'SRINU',2300,3)

INSERT INTO EMPLOYEES_DATA VALUES (7,'KARTHIK',3500,33)

INSERT INTO EMPLOYEES_DATA VALUES (7,'SURYA12',3500,33)

INSERT INTO EMPLOYEES_DATA VALUES (9,'456',3500,33)

INSERT INTO EMPLOYEES_DATA VALUES (10,JOHNSON,500,13)

SELECT *FROM EMPLOYEES_DATA

UPDATE:

UPDATE EMPLOYEES_DATA SET EMPID=4 WHERE EMPID=473289

UPDATE EMPLOYEES_DATA SET SALARY=9000 WHERE EMPNAME='SMITH'

UPDATE EMPLOYEES_DATA SET EMPID=17 WHERE EMPNAME='KARTHIK'

DELETE:

DELETE EMPLOYEES_DATA WHERE EMPID=4

DELETE EMPLOYEES_DATA


SELECT *FROM EMPLOYEES_DATA

DELETE EMPLOYEES_DATA WHERE EMPID=2

DELETE EMPLOYEES_DATA

TRUNCATE:

TRUNCATE TABLE EMPLOYEES_DATA

DROP:

DROP TABLE EMPLOYEES_DATA
