USE AMAZON

/* IDENTITY (SEED / INCREMENT) CONCEPT */

CREATE TABLE CUSTOMERS (CUSTOMER_ID INT IDENTITY(21,1),
                        PRODUCT_NAME CHAR(10),
						PRODUCT_PRICE MONEY)

SELECT *FROM CUSTOMERS

INSERT INTO CUSTOMERS VALUES ('RICEBAG',1200)
INSERT INTO CUSTOMERS VALUES ('OIL',1500)
INSERT INTO CUSTOMERS VALUES ('MAGGI',10)

INSERT INTO CUSTOMERS VALUES (4,'ICECREAM',120)

DROP TABLE CUSTOMERS

/* SQL Set Operations */

CREATE TABLE EMPLOYESS (EMPID INT,EMPNAME CHAR(10),EMPAGE TINYINT)
CREATE TABLE STUDENT (STDID INT,STDNAME CHAR(10),STDAGE TINYINT)

SELECT *FROM EMPLOYESS
SELECT *FROM STUDENT

INSERT INTO EMPLOYESS VALUES (1,'JOHN',27)
INSERT INTO EMPLOYESS VALUES (2,'PETER',37)
INSERT INTO EMPLOYESS VALUES (3,'STEVE',25)
INSERT INTO EMPLOYESS VALUES (4,'BRAD',32)
INSERT INTO EMPLOYESS VALUES (5,'SMITH',43)

UNION:

SELECT *FROM EMPLOYESS
UNION
SELECT *FROM STUDENT

SELECT *FROM EMPLOYESS
UNION ALL
SELECT *FROM STUDENT

SELECT *FROM EMPLOYESS
SELECT *FROM STUDENT
SELECT *FROM EMPLOYESS
INTERSECT 
SELECT *FROM STUDENT

SELECT *FROM EMPLOYESS
SELECT *FROM STUDENT
SELECT *FROM EMPLOYESS
EXCEPT 
SELECT *FROM STUDENT
