/* CREATE OWN DATABASE */
CREATE DATABASE AMAZON

/* ACTIVATE DATABASE */
USE AMAZON

/* DDL OPERATIONS */
CREATE TABLE EMPLOYEE_DETAILS (EMPNAME CHAR(10),EMPAGE TINYINT,EMPSALARY MONEY)

/* WANT TO SHOW THE TABLE */
SELECT *FROM EMPLOYEE_DETAILS

/* ALTER */
ALTER TABLE EMPLOYEE_DETAILS ALTER COLUMN  EMPAGE INT 

ALTER TABLE EMPLOYEE_DETAILS ADD EMPLOC CHAR(10)

ALTER TABLE EMPLOYEE_DETAILS DROP COLUMN EMPSALARY 

ALTER TABLE EMPLOYEE_DETAILS RENAME COLUMN EMPAGE to EMPID

/* SP_RENAME -> CHANGE THE COLUMN NAME */
SP_RENAME 'EMPLOYEE_DETAILS.EMPLOC','EMPAREA'

/* DML OPERATIONS */
INSERT INTO EMPLOYEE_DETAILS VALUES ('JOHN',27,1200)
INSERT INTO EMPLOYEE_DETAILS VALUES ('PETER',37,180)
INSERT INTO EMPLOYEE_DETAILS VALUES ('MICHEAL',17,100)
INSERT INTO EMPLOYEE_DETAILS VALUES ('BRAD',41,1800)
INSERT INTO EMPLOYEE_DETAILS VALUES ('HENRY',23,1300)

/* UPDATE */
UPDATE EMPLOYEE_DETAILS SET EMPAREA=800 WHERE EMPNAME='BRAD'
UPDATE EMPLOYEE_DETAILS SET EMPAGE=47 WHERE EMPNAME='MICHEAL'


/* DELETE */
DELETE EMPLOYEE_DETAILS
DELETE EMPLOYEE_DETAILS WHERE EMPNAME='BRAD'
/* TRUNCATE */
TRUNCATE TABLE EMPLOYEE_DETAILS 

/* DROP */

DROP TABLE EMPLOYEE_DETAILS

SELECT *FROM EMPLOYEE_DETAILS
