/* DQL OPERATIONS */

PROJECTION_METHOD:

SELECT *FROM EMPLOYEE_DETAILS

SELECTION_METHOD:
SELECT EMPID,EMPNAME FROM EMPLOYEE_DETAILS

/*JOINS*/
SELECT *FROM EMPLOYEE
SELECT *FROM STUDENT

TRUNCATE TABLE EMPLOYEE
TRUNCATE TABLE STUDENT 

INSERT INTO EMPLOYEE VALUES (1,'JOHN',27)
INSERT INTO EMPLOYEE VALUES (2,'PETER',21)
INSERT INTO EMPLOYEE VALUES (3,'MICHEAL',33)
INSERT INTO EMPLOYEE VALUES (4,'BRAD',37)
INSERT INTO EMPLOYEE VALUES (5,'STEVE',40)
INSERT INTO EMPLOYEE VALUES (6,'HUSSY',19)
INSERT INTO EMPLOYEE VALUES (7,'SMITH',41)




INSERT INTO STUDENT VALUES (11,'KIRAN',43)
INSERT INTO STUDENT VALUES (3,'KUMAR',12)
INSERT INTO STUDENT VALUES (12,'PRAVEEN',22)
INSERT INTO STUDENT VALUES (13,'GOUTHAM',12)
INSERT INTO STUDENT VALUES (5,'SRINU',15)
INSERT INTO STUDENT VALUES (14,'LOLLY',19)
INSERT INTO STUDENT VALUES (15,'LAYA',17)


SELECT *FROM EMPLOYEE
SELECT *FROM STUDENT

INNER_JOIN:
SELECT *FROM EMPLOYEE INNER JOIN STUDENT ON EMPLOYEE.EMPID=STUDENT.STDID

LEFT_OUTER_JOIN:
SELECT *FROM EMPLOYEE LEFT OUTER JOIN STUDENT ON EMPLOYEE.EMPID=STUDENT.STDID

RIGHT_OUTER_JOIN:
SELECT *FROM EMPLOYEE RIGHT OUTER JOIN STUDENT ON EMPLOYEE.EMPID=STUDENT.STDID

FULL_OUTER_JOIN:
SELECT *FROM EMPLOYEE FULL OUTER JOIN STUDENT ON EMPLOYEE.EMPID=STUDENT.STDID

CROSS_JOIN:
SELECT *FROM EMPLOYEE CROSS JOIN STUDENT

EQUI_JOIN:
SELECT *FROM EMPLOYEE,STUDENT WHERE EMPLOYEE.EMPID = STUDENT.STDID

NON_EQUI_JOIN:
SELECT *FROM EMPLOYEE,STUDENT WHERE EMPLOYEE.EMPAGE > STUDENT.STDAGE
