SELECT *FROM EMPLOYEE_DETAILS

CREATE TABLE STUDENT_DETAILS (STDID TINYINT IDENTITY,STDNAME CHAR(10),STDDEPT CHAR(10))

SELECT *FROM STUDENT_DETAILS

SET IDENTITY_INSERT STUDENT_DETAILS ON 
INSERT INTO STUDENT_DETAILS (STDID,STDNAME,STDDEPT) VALUES (11,'JOHN','MECH')
INSERT INTO STUDENT_DETAILS (STDID,STDNAME,STDDEPT) VALUES (12,'PETER','CIVIL')
INSERT INTO STUDENT_DETAILS (STDID,STDNAME,STDDEPT) VALUES (13,'MICHEAL','MECH')
INSERT INTO STUDENT_DETAILS (STDID,STDNAME,STDDEPT) VALUES (14,'BRAD','CSE')
INSERT INTO STUDENT_DETAILS (STDID,STDNAME,STDDEPT) VALUES (15,'RANDY','ECE')

TRUNCATE TABLE STUDENT_DETAILS 
DROP TABLE STUDENT_DETAILS

/* PRIMARY KEY AND FORGEIN KEY */

CREATE TABLE EMP_JOB_DETAILS (ID INT PRIMARY KEY,EMPNAME CHAR(10),EMPAGE TINYINT)

CREATE TABLE EMP_PER_DETAILS (EMPLOC CHAR(10),EMPSALARY MONEY,EMPTAX MONEY,ID INT FOREIGN KEY REFERENCES  EMP_JOB_DETAILS(ID) ON UPDATE CASCADE ON DELETE CASCADE)

SELECT *FROM EMP_JOB_DETAILS
SELECT *FROM EMP_PER_DETAILS

INSERT INTO EMP_JOB_DETAILS VALUES (1,'JOHN',27)
INSERT INTO EMP_JOB_DETAILS VALUES (2,'PETER',22)
INSERT INTO EMP_JOB_DETAILS VALUES (3,'MICHEAL',32)
INSERT INTO EMP_JOB_DETAILS VALUES (4,'BRAD',44)
INSERT INTO EMP_JOB_DETAILS VALUES (5,'STEVE',41)

INSERT INTO EMP_PER_DETAILS VALUES ('HYD',1200,12,1)
INSERT INTO EMP_PER_DETAILS VALUES ('USA',1400,11,2)
INSERT INTO EMP_PER_DETAILS VALUES ('UK',1800,9,3)
INSERT INTO EMP_PER_DETAILS VALUES ('PARIS',800,20,10)
INSERT INTO EMP_PER_DETAILS VALUES ('DELHI',1100,18,4)

INSERT:
INSERT INTO EMP_JOB_DETAILS VALUES (6,'KIRAN',30)
INSERT INTO EMP_PER_DETAILS VALUES ('AP',2400,30,5)

UPDATE:
UPDATE EMP_JOB_DETAILS SET EMPAGE=62 WHERE EMPNAME='MICHEAL'

UPDATE EMP_PER_DETAILS SET EMPTAX=90 WHERE EMPLOC='UK'

DELETE:
DELETE EMP_JOB_DETAILS WHERE EMPNAME='KIRAN'

DELETE EMP_PER_DETAILS WHERE EMPLOC='USA'

/* CASCADE RULES */
DROP TABLE EMP_JOB_DETAILS
DROP TABLE EMP_PER_DETAILS


UPDATE EMP_JOB_DETAILS SET ID=40 WHERE ID=4

DELETE EMP_JOB_DETAILS WHERE EMPNAME='PETER'
