/* PRIMARY KEY AND FOREIGN KEY */

CREATE TABLE EMPLOYEE_OFFICE_DETAILS (EMP_ID INT PRIMARY KEY,EMP_NAME CHAR(10),EMP_SALARY MONEY)

CREATE TABLE EMPLOYEE_PERSONAL_DETAILS (EMP_LOC CHAR(10),EMP_P_COM CHAR(20),EMP_P_SA MONEY,EMP_ID INT FOREIGN KEY REFERENCES EMPLOYEE_OFFICE_DETAILS(EMP_ID) ON UPDATE CASCADE ON DELETE CASCADE)


INSERT INTO EMPLOYEE_OFFICE_DETAILS VALUES (10,'JOHN',100),(20,'PETER',90),(30,'STEVE',110),(40,'MICHEAL',92),(50,'KIRAN',96)


SELECT *FROM EMPLOYEE_OFFICE_DETAILS
SELECT *FROM EMPLOYEE_PERSONAL_DETAILS

INSERT INTO EMPLOYEE_PERSONAL_DETAILS VALUES ('DELHI','IBM',66,10)
INSERT INTO EMPLOYEE_PERSONAL_DETAILS VALUES ('PUNE','INFOSYS',56,20)
INSERT INTO EMPLOYEE_PERSONAL_DETAILS VALUES ('NOIDA','GOOGLE',46,30)
INSERT INTO EMPLOYEE_PERSONAL_DETAILS VALUES ('BANGALORE','MSFT',88,40)
INSERT INTO EMPLOYEE_PERSONAL_DETAILS VALUES ('HYD','META',72,50)


INSERT INTO EMPLOYEE_PERSONAL_DETAILS VALUES ('CHENNAI','JPMOR',65,100)



INSERT_INTO_PARENT:
INSERT INTO EMPLOYEE_OFFICE_DETAILS VALUES (60,'CENA',110)

INSERT_INTO_CHILD:
INSERT INTO EMPLOYEE_PERSONAL_DETAILS VALUES ('ANDRA','CYIENT',78,60)

UPDATE_INTO_PARENT:
UPDATE EMPLOYEE_OFFICE_DETAILS SET EMP_SALARY=120 WHERE EMP_NAME='STEVE'

UPDATE_INTO_PARENT_PRIMARY_COLUMN: /* NOT POSSIBLE */
UPDATE EMPLOYEE_OFFICE_DETAILS SET EMP_ID=500 WHERE EMP_NAME='KIRAN'

DELETING_INTO_PARENT:
DELETE FROM EMPLOYEE_OFFICE_DETAILS WHERE EMP_ID=50

UPDATE_IN_CHILD:
UPDATE EMPLOYEE_PERSONAL_DETAILS SET EMP_P_SA=77 WHERE EMP_P_SA=72

DELETE_FROM_CHILD:
DELETE FROM EMPLOYEE_PERSONAL_DETAILS WHERE EMP_P_SA=77


CASCADE_RULES:

UPDATE EMPLOYEE_OFFICE_DETAILS SET EMP_ID=400 WHERE EMP_ID=40

DELETE EMPLOYEE_OFFICE_DETAILS WHERE EMP_ID=50
